title: ML in Health Science
logo: /assets/img/logo.png
description: Machine Learning in Health science is a specialized token crafted to drive and reward innovation in the integration ML in health sciences. $MLHS
show_downloads: true
google_analytics:
theme: jekyll-theme-minimal
